version: "3.0"

services:
  redis:
    image: redis:alpine

  mysql:
    image: ibex/debian-mysql-server-5.7
    volumes:
      - mysql-data:/var/lib/mysql

  idp-api:
    image: "idp-api:latest"
    environment:
      - App__SelfUrl=http://abp-vue-idp.dd.ixq-soft.cn:8080
      - App__CorsOrigins=http://*.dd.ixq-soft.cn:8080
    depends_on:
      - redis
      - mysql

  host-api:
    image: "host-api:latest"
    environment:
      - App__CorsOrigins=http://*.dd.ixq-soft.cn:8080
    depends_on:
      - redis
      - mysql
      - idp-api

volumes:
  mysql-data: